/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n7.0.1-11-g40ddddca45-20240630"
#endif /* AVUTIL_FFVERSION_H */
